version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
       AfterInstall:
    - location: scripts/set-permissions.sh
      timeout: 300
      runas: ubuntu
